apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
  encrypted: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true